# Generated by Django 3.1.7 on 2021-03-09 08:40

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('estate', '0002_auto_20210224_2252'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donate', models.BooleanField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estate.estateitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemPriority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)])),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estate.estateitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='estateitem',
            name='donate_or_throw',
            field=models.ManyToManyField(blank=True, related_name='uservotes', through='estate.ItemVote', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='estateitem',
            name='wants_item',
            field=models.ManyToManyField(blank=True, related_name='userpriorities', through='estate.ItemPriority', to=settings.AUTH_USER_MODEL),
        ),
    ]
