# Generated by Django 3.1.7 on 2021-04-01 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0003_auto_20210316_1353'),
        ('estate', '0003_auto_20210309_0840'),
    ]

    operations = [
    ]
