# Generated by Django 3.1.7 on 2021-04-06 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0005_estateitem_given_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='estateitem',
            name='donated_or_thrown',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
