# Generated by Django 3.1.7 on 2021-04-06 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0006_estateitem_donated_or_thrown'),
    ]

    operations = [
        migrations.AddField(
            model_name='estate',
            name='is_settled',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
